version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - ireturn
    - nonamedreturns
    - varnamelen
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      enabled-tags:
        - opinionated
        - diagnostic
        - style
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
